<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="chassis_length" value="0.439166"/>
    <xacro:property name="chassis_width" value="0.396748"/>
    <xacro:property name="chassis_height" value="0.2159"/>
    <xacro:property name="chassis_mass" value="13.6078"/>
    <xacro:property name="wheel_radius" value="0.048"/>
    <xacro:property name="wheel_thickness" value="0.038"/>
    <xacro:property name="wheel_mass" value="0.207"/>
    <xacro:property name="wheel_offset_x" value="${chassis_length/2}"/>
    <xacro:property name="wheel_seperation" value="0.417"/>
    <xacro:property name="wheel_offset_y" value="${wheel_seperation/2}"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="${wheel_radius}"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <!-- <xacro:include filename="robot_core.xacro"/> -->

    <xacro:property name="lidar_radius" value="0.05"/>
    <xacro:property name="lidar_length" value="0.04"/>
    <xacro:property name="lidar_x_offset" value="0.385"/>

    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <!-- <origin xyz="${lidar_radius} 0 0.05" rpy="0 0 0"/> -->
        <origin xyz="${chassis_length - lidar_radius} 0 0.05" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="0.04"/>
            </geometry>
            <material name="black"/>
        </visual>
        <visual>
            <origin xyz="0 0 -0.05"/>
            <geometry>
                <cylinder radius="0.01" length="0.1"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>



    <gazebo reference="laser_frame">
        <material>Gazebo/Black</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.5</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>
